export const COLORS_MAP = {
  black: "--c-black",
  blackSoft: "--c-black-soft",
  white: "--c-white",
  greenPrimary: "--c-green-primary",
  greenSecondary: "--c-green-secondary",
  greenLight: "--c-green-light",
  greenDark: "--c-green-dark",
  greenLime: "--c-green-lime",
  greenLimeSoft: "--c-green-lime-soft",
  cream: "--c-cream",
  redPrimary: "--c-red-primary",
  blackOverlay: "--c-black-overlay",
  grayLight: "--c-gray-light",
};
